echo "my name is riyal"
echo "I am learning full stack"
echo "I don't want any conflicts"
echo "Hello, How are you?"
echo "Batch-20 HELLO"
#echo "We are learning Git for branching strategy"
#echo "We are modifying code for feature-1"
