echo "I don't want any conflicts"
echo "my name is ritu"
echo "I am learning aws"
echo "I am trying to create merge conflicts"
echo "Hello, How are you?"
echo "We are learning Git for branching strategy"
echo "We are modifying code for feature-1"
echo "This is batch-20"
